import Head from 'next/head'
import Link from 'next/link'

//sanity client with prebuilt configs
import {
  sanityClient,
  urlFor
} from '../lib/sanity';


const recipeQuery = `*[_type == recipe]`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
